### ISSUE TITLE
Flashing with FPT errors out after first successful flash

### ISSUE THREAD

**Issue by ms178** [BIOS-iEngineer/HUANANZHI-X99-TF#2]
Hello,

thanks for your work. I've tried a modded version of your CX99DE26 BIOS release on a Jingsha X99-8D3 (it is the DDR3 version of the X99-D8). I modded it with the turbo boost unlock and removed the Haswell microcode. I used FPT for flashing the ROM under Windows and the first flash was succesful as everything works so far, which is the good news (the ECC functionality does also work correctly under Linux with your BIOS, the stock BIOS of that board had some issues, also one could get a newer BIOS version from SZMZ - the producer of that board - which solves that issue, too).

After editing some more settings with AMIBCP, I tried to re-flash the newly modified file with FPT but now I do get the following error:
![x99_fpt_bios_error](https://user-images.githubusercontent.com/19559105/95993710-b9e55b80-0e2f-11eb-8563-60cf869808b3.png)

I haven't tried other methods to flash it yet and don't have a programmer at hand. Is there a way to fix this? Would it work with AfuEFI with the command as shown in your picture?

**Comment by BIOS-iEngineer** [comment]
Hello, if you do not have a programmer, then you can flash the BIOS area with the command indicated in the picture, the latest version of Afuefix64.efi is in the repository.

**Comment by ms178** [comment]
Thanks for the clarification. By the way, I don't see the option in the boot menu to boot into the built-in efi shell. This option existed in the original BIOS however.  Is that a bug? I guess I need to figure out how to boot Efi Shell from a prepared USB stick then...

**Comment by ms178** [comment]
... and I found out how to do it. It worked. For other people stumbling upon this issue, you need a FAT32 formatted USB stick (Rufus can do it even for larger capacity sticks), for the Efi Shell one needs bootx64.efi and bootia32.efi which can be found on the internet (e.g. tianocore project offers them under different file names) and copy them into the efi/boot directory of that USB stick which you have to create on the stick - don't forget to copy also the BIOS file and AfuEFIx64 in the root directory, too. Re-boot and boot from that USB stick - it should be offered with the UEFI prefix in the BIOS menu. Once you are in the EFI shell you will see several fs-entries, find out which one fits your USB stick - in my case it was fs0 - then I typed `fs0:` to get on that device and after that you could type `dir` to show the contents of that directory. From now on the command from BIOS-iEngineer on the front page should lead to a successful flash.

**Comment by BIOS-iEngineer** [comment]
EFI Shell is now used as a boot option with no alternative. If the system doesn't have boot devices
