### ISSUE TITLE
CPU fan speed is not controlled after S3 Sleep

### ISSUE THREAD

**Issue by rand256** [BIOS-iEngineer/HUANANZHI-X99-TF#3]
On a clean start, CPU fan speed is controlled by the CPU temperature: the more system load, the more heat is produced, the faster fan rotates. But if the system was put into Sleep (Suspend-to-RAM), then after awakening CPU fan isn't controlled anymore: it always rotates on the same speed regardless of current system load.

After full system restart the fan control is regained.
Also after Hibernation (Suspend-to-Disk) the issue doesn't happen, it is only S3 that breaks fan controls.

**Comment by BIOS-iEngineer** [comment]
Your problem is not confirmed on the test board of this BIOS. Maybe you've make some changes to the BIOS obrose that you keep quiet about, or malfunction of your board.

**Comment by vikipetrov96** [comment]
У меня инженерный биос последней ревизии,Могу сказать точно
перед сном RPM 830 и изменения
после сна RPM 1260 эти значения не снижаются
В стресс-тесте Aida повышается температура но,RPM 1250,1260 не меняется, вращается с одной скоростью.
Так после сна температура поднимается и опускается,но вентилятор не работает вращается с одной скоростью,такое же поведение с товарным биосом,стоковая биография
вы решаете, работает ли это для меня, это не работает,Это материнская плата Huanan X99-TF.E5 2678v3 без разблокировки процессора.

PP:Я забыл добавить 53C температуру материнской платы перед сном,а после засыпания 122С не меняется и остается кодом 73.
![IMG_20201019_173432](https://user-images.githubusercontent.com/71845213/96468969-5dba7700-1235-11eb-8924-45d134cfa206.jpg)
![Екранна снимка (2)](https://user-images.githubusercontent.com/71845213/96469012-68750c00-1235-11eb-8c82-6b86311bb4eb.png)
![Екранна снимка (3)](https://user-images.githubusercontent.com/71845213/96469017-6b6ffc80-1235-11eb-998b-65fd9ff232c0.png)

**Comment by vikipetrov96** [comment]
> Your problem is not confirmed on the test board of this BIOS. Maybe you've make some changes to the BIOS obrose that you keep quiet about, or malfunction of your board.

I have exactly the same problem I posted pictures in the BIOS no settings are touched, everything is default

**Comment by rand256** [comment]
> Your problem is not confirmed on the test board of this BIOS. Maybe you've make some changes to the BIOS obrose that you keep quiet about, or malfunction of your board.

Probably your board is not like the others, or, what is more likely, your "confirmation test" is simply invalid.

This issue is completely the same on factory X99-TF BIOS (all versions), Jingsha X99-D8 BIOS (latest two versions at least) and, unfortunately, your BIOS with all default settings. I assume all of them are actually using a similar module for S3 restoration, with the same issues. This is confirmed by several different people from overclockers.ru community forums. Though you'd may say that all those boards are spontaneously malfunctioned - what a coincidence!

To illustrate, this is a picture from a D8 board with its factory BIOS.
![peci-sleep](https://user-images.githubusercontent.com/30267719/96544746-d100cf00-12af-11eb-84b0-6d1c341a18e2.jpg)

Regarding to S3 behavior, your BIOS is different from this one in that yours is always reporting CPU PECI around 40C after S3, and D8's shows wrong negative values. Both are having the same issue with CPU FAN speed stuck at around 50% regardless of CPU load after S3.

**Comment by vikipetrov96** [comment]
Dude, you don't know me, I'm not lying
I'm telling you about this problem so you know
I do everything with good feelings,not only I have this problem a lot
people both in Russia and here in Bulgaria.
Like I told you there is a problem with the speed of RPM AFTER
SLEEPING,everything in the bios is the default.
I don't understand much about Bios almost nothing but I see this problem.
I am very grateful to you for what you pay homage and respect.

На вт, 20.10.2020 г. в 8:52 Erinome <notifications@github.com> написа:

**Comment by vikipetrov96** [comment]
Dude, you don't know me, I'm not lying
I'm telling you about this problem so you know
I do everything with good feelings,not only I have this problem a lot people both in Russia and here in Bulgaria.
Like I told you there is a problem with the speed of RPM AFTER SLEEPING,everything in the bios is the default.
I don't understand much about Bios almost nothing but I see this problem.
I am very grateful to you for what you pay homage and respect.
![Екранна снимка (5)](https://user-images.githubusercontent.com/71845213/96567566-9a3ab100-12cf-11eb-9837-e601f7a11a78.png)
![Екранна снимка (6)](https://user-images.githubusercontent.com/71845213/96567575-9c9d0b00-12cf-11eb-967f-3aedcc13fc47.png)
