### ISSUE TITLE
Enabling Cluster on Die leads to "(A7) Me FW Downgrade - Request MeSpiLock Failed" error

### ISSUE THREAD

**Issue by ms178** [BIOS-iEngineer/HUANANZHI-X99-TF#4]
Hello,

I came across the following error message after enabling the Cluster on Die (COD) functionality under the QPI settings: "(A7) Me FW Downgrade - Request MeSpiLock Failed" 

There was a second error message around half a minute later and then the Boot process went on with some delay, but in Windows (Windows 10 20241 Insider Preview) I cannot see the two clusters, only one - just as before. Normally when enabling this functionality two seperate clusters can be seen in the task manager under the CPU section. Hence it should be easy to verify if it works or not as intended. 

Just a warning if someone else wants to replicate it: The first time I saw this I powered off my computer when the error message popped up and the mainboard wouldn't even power on again, only a CMOS reset brought it back to life. It takes some time to finish but it will boot eventually. I am using a modified version of your 10-10-2020 release of the Hunanzhi X99-TF BIOS on a Jingsha X99-8D3. My modifications: I've deleted the Haswell-EP microcode, injected the Turbo Boost Unlock driver and updated to a newer Intel SATA OROM/EFI.

**Comment by BIOS-iEngineer** [comment]
Hello!
Cluster on Die (COD) does not work in current configuration on _**MCC, HCC**_ & **LCC** processors for any motherboards. **Settings menu for QPI is hidden, development is not planned.**
Read more about Intel Cluster-On-Die(COD) technology: [**Here**](https://www.dell.com/support/article/en-us/sln315049/intel-cluster-on-die-cod-technology-on-vmware-esxi?lang=en)

Latest Intel **RSTe** EFI "RaidDriver" **modules from the v5 platform:** is Intel **RSTe** EFI SATA "RaidDriver" v**5.5.5.1005** for **DEV:2826**

**Comment by ms178** [comment]
Hello,

these contradicts my own findings with the original Jingsha BIOS (the one I attached below) and Huananzhi BIOS versions (August 2020 release) which I tried and had no problems with the Cluster-on-Die functionality and worked fine with it enabled (I tested this myself). Maybe there is some incompatibility with the newer ME firmware which you included or some other change you made? I'll attach my modded SZMZ BIOS (-50/-20 mV) for the Jingsha X99-8D3 for reference. If you don't want to support that fucntionality that would be a reason to run with the original SZMZ BIOS for me again - as I found my best RAM settings already and I can program them into the BIOS with AMIBCP and your unlocked XMP menue would be the only advantage for your BIOS left as I can mod all the other parts myself with UBUTool.

By the way, I had no problems inserting the Intel-RSTe_EFI-sSATA-RaidDriver_v7.0.0.2086 EFI driver in your BIOS - you can insert these with UBUTool which you can find on the Win-Raid forums where you could get the RaidDriver files as well. I currently run that EFI driver and run on it with the 7.0.0.2286 sSATA Windows driver. It might not be officially supported by Intel, but it does work so far (I haven't tried the RAID functionality though - just a single Samsung SATA SSD on one of the sSATA ports). :)

Have a nice Sunday,
ms178

[mod_SZMZ_mod5020.zip](https://github.com/BIOS-iEngineer/HUANANZHI-X99-TF/files/5434310/mod_SZMZ_mod5020.zip)

**Comment by ms178** [comment]
Hello again,

after re-flashing the SZMZ BIOS with AfuEFI (using the additional "force" option), I see some strange behavior with that board which wasn't there before flashing your BIOS: 1) The board now needs 2-boot cycles to come up and 2) the same issue with COD now also shows up here. I will try to re-flash it with FPT and see how that goes...

**Comment by BIOS-iEngineer** [comment]
Please **use a programmer device** if you are using a third party BIOS. This is not a problem with the BIOS that I make, it is a condition in the absence of manufacturer standards.

**Comment by ms178** [comment]
Sorry if that sounded as blaming your work - I am thankful that someone knowledgable puts some love into the BIOS of these boards. It is just that the prior BIOS versions worked flawlessly with FPT and that BIOS option, I don't have a programmer at hand (like most enthusiasts trying out your BIOS, I'd assume) and I wasn't too familiar with AfuEFI. I got my board in a more stable state now and I know that I took a high risk here - I just wanted to post this issue for you and others to be aware of these issues (if you were aware of these beforehand, please state such remaining issues in the release notes as it is a functional regression when coming from the original BIOS and might people re-consider flashing it). 

Concerning the COD functionality, my prior testing revealed better memory latency and L3 cache results in AIDA64 with that option enabled. I've also read several white papers on that feature for a better understanding. Today's games don't seem to like it though, my two favorite games regressed significantly (20 - 30%) albeit the frame times in one game were smoother (my 12-Core gets separeted into two NUMA nodes wheras Windows schedules the game on one node while the other just handles small background tasks). I suppose how it works today most games are not NUMA-friendly at all, especially with the current state of the Windows scheduler. But nevertheless that option might be handy for people with NUMA-friendly workloads (or using Linux) and although you are not planning to support it right now, maybe that will change in the future. From my end-user perspective more options are always welcome and there might be users out there which need this option but obviously I don't know how much work it would be to implement that functionality. :)

**Comment by BIOS-iEngineer** [comment]
For support COD need use servers SPS, ME is intended for Workstation
