### ISSUE TITLE
Ability to select primary video adapter Hi there, thank you for the great work at the first. 

### ISSUE THREAD

**Issue by mosquito** [BIOS-iEngineer/HUANANZHI-X99-TF#6]
Please help me understand how I can select the primary video adapter? As I can guess that's not possible on the stock firmware.

On my case I have to use third PCI-e port as primary video adapter but on the second port installed video adapter which using only as computing module without video output.

Please say is it possible, might be you can help me patch for this?

**Comment by BIOS-iEngineer** [comment]
Hallo! The development of this bios has long been completed, the board has broken down safely, you can try the bios from the F8 board using the programmer, as in version 28 the ability to give 8-PCIe lines for the 3rd slot is implemented.
