### ISSUE TITLE
Flash WINBOND25018JVSQ

### ISSUE THREAD

**Issue by Schaka** [BIOS-iEngineer/HUANANZHI-X99-TF#7]
Hi,

I couldn't find another way of contacting you, so please excuse me for abusing the issue tracker.
I noticed you referenced this chip in the readme and I have a bricked board which uses it, but AsProgrammer does not offer flashing to it in its list. What software do you recommend I use? This is for a ZX_99EV, unfortunately. I have already ordered the X99-TF board, but would like to still try and fix what I have as well.

**Comment by BIOS-iEngineer** [comment]
Hi!
https://github.com/BIOS-iEngineer/HUANANZHI-X99-F8/issues/8 
25Q128 The overall called chip
